version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    # NVIDIA GPUを利用する場合は、以下のオプションを有効にしてください（Docker環境に依存します）。
    runtime: nvidia
    # または device_requests を利用する場合（Docker Compose v2.4以降）
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

  tika:
    image: apache/tika:latest-full
    container_name: tika
    ports:
      - 9998:9998
    restart: unless-stopped

  open-webui:
    # カスタムビルドする場合は、以下の build オプションのコメントを解除してください。
    # build: ./open-webui
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    # environment:
    #   - WEBUI_AUTH=False  # 新規ユーザー登録画面をスキップ
    volumes:
      - open_webui_data:/app/backend/data
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  ollama_data:
  open_webui_data:
